<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="vimal" failures="1" tests="3" name="Test" time="9.911" errors="0" timestamp="2024-12-24T13:26:15 IST">
  <testcase classname="day46.OrangeHrmTestAgain" name="testLogo" time="2.743"/>
  <testcase classname="day46.OrangeHrmTestAgain" name="testUrl" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [toFail] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [toFail] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day46.OrangeHrmTestAgain.testUrl(OrangeHrmTestAgain.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testUrl -->
  <testcase classname="day46.OrangeHrmTestAgain" name="tsetTitle" time="0.0">
    <skipped/>
  </testcase> <!-- tsetTitle -->
</testsuite> <!-- Test -->
